name: build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Test
        run: poetry run pythoncz test

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Deploy
        run: pipenv run pythoncz deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
